steps:
  # Terraform fmt
  - name: "hashicorp/terraform:1.5.7"
    id: fmt
    args: ["fmt", "-check"]

  # Terraform init
  - name: "hashicorp/terraform:1.5.7"
    id: init
    args: ["init"]

  # Terraform validate
  - name: "hashicorp/terraform:1.5.7"
    id: validate
    args: ["validate"]

  # Terraform plan
  - name: "hashicorp/terraform:1.5.7"
    id: plan
    args: ["plan", "-var-file=vars/vars.tfvars",'-out=tfplan']

  # Terraform apply
  - name: "hashicorp/terraform:1.5.7"
    id: apply
    args: ['apply', '-auto-approve', 'tfplan']

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: "projects/playground-adnan/serviceAccounts/custom-cloudbuild-sa@playground-adnan.iam.gserviceaccount.com"
